#!/bin/sh
# Install the Omarchy bar plugin from this repo.
#
# The repo is the source of truth; the plugin folder is a *copy* of it —
# `omarchy plugin validate` refuses symlinks inside a plugin folder, and the
# shell hot-reloads a local plugin on any file change inside that folder, so the
# app (panel, CLI, n8n flows) must not live there. Only the shell's own files are
# copied: manifest + QML + views/components + i18n + assets.
#
#   ./install.sh                  -> ~/.config/omarchy/plugins/custom.jira
#   PLUGIN_DIR=/tmp/t ./install.sh -> somewhere else (a test)
#
# Re-run after `git pull` when the QML, i18n or manifest changed. Edits to the
# app (bin/, panel/, n8n/) need no reinstall: the shims below point at this repo.
set -eu

root=$(cd "$(dirname "$0")" && pwd)
dir=${PLUGIN_DIR:-$HOME/.config/omarchy/plugins/custom.jira}

mkdir -p "$dir"
for p in manifest.json BarWidget.qml JiraPanel.qml components views i18n assets; do
	rm -rf "$dir/$p"
	cp -r "$root/$p" "$dir/$p"
done

# The widget and the panel run the app's CLIs, which live outside this folder.
# One generated shim per CLI keeps the QML's ../../../bin/<name>.py paths working
# while editing the app stays a no-op for the shell.
mkdir -p "$dir/bin"
for name in jira_bridge.py jira_flow.py; do
	cat > "$dir/bin/$name" <<EOF
#!/usr/bin/env python3
"""Generated by install.sh. The real CLI lives in $root/bin/$name."""
import os, sys
os.execv(sys.executable, [sys.executable, "$root/bin/$name", *sys.argv[1:]])
EOF
	chmod +x "$dir/bin/$name"
done

omarchy plugin validate "$dir"
omarchy-shell shell rescanPlugins >/dev/null 2>&1 || true
echo "plugin installed: $dir (app: $root)"
